"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 4

[palette]
os = "#ACB0BE"
closer = "p:os"
pink = "#F5C2E7"
lavender = "#B4BEFE"
blue = "#89B4FA"

[[blocks]]
alignment = "left"
type = "prompt"
  [[blocks.segments]]
    foreground = "p:blue"
    style = "plain"
    template = "{{ .UserName }}:{{ .HostName }} "
    type = "session"
  [[blocks.segments]]
    foreground = "p:pink"
    style = "plain"
    template = "{{ .Path }} "
    type = "path"
  [[blocks.segments]]
    foreground = "p:lavender"
    template = "{{ .HEAD }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }} "
    style = "plain"
    type = "git"
  [blocks.segments.options]
    branch_icon = " "
    cherry_pick_icon = " "
    commit_icon = " "
    fetch_status = true
    fetch_upstream_icon = true
    merge_icon = " "
    no_commits_icon = " "
    rebase_icon = " "
    revert_icon = " "
    tag_icon = " "
[[blocks]]
  alignment = "right"
  type = "prompt"
  [[blocks.segments]]
    type = "go"
    style = "plain"
    template = "  {{ .Full }} "
  [[blocks.segments]]
    type = "python"
    style = "plain"
    template = "  {{ .Full }} "


[[blocks]]
alignment = "left"
type = "prompt"
  [[blocks.segments]]
    style = "plain"
    foreground = "p:closer"
    template = ""
    type = "text"

[maps.user_name]
szelam = "󰊠"
root = ""

[maps.host_name]
szelamMacBookPro = ""
